#:mute

#:def ADDPROP(name,*args)
$:fyppmacros.AddProp(name, *args)
#:enddef ADDPROP

#:def GENERATESTRUCTS(*args, **kwargs)
$:fyppmacros.GenStructs()
#:enddef GENERATESTRUCTS


$:fyppmacros.setvar("ndim", NDIM)

#:include 'ppiclf_user_particle_original.fhpp'

#:endmute

$:fyppmacros.FinalizeParticleStruct()


#:def DECLAREPARTVAR(*args)
$:fyppmacros.DeclarePartVar(*args)
#:enddef DECLAREPARTVAR



#:def USEMODVAR(PPICLF_t_particle, ppiclf_parts)
$:fyppmacros.ImportModVar(PPICLF_t_particle, ppiclf_parts)
#:enddef USEMODVAR

#:def LISTCOMPONENTS(*args)
$:", ".join(fyppmacros.ListComponents(*args))
#:enddef LISTCOMPONENTS

#:def USEPARTICLE(*args)
$:fyppmacros.GenPropAccess(*args)
#:enddef USEPARTICLE

#:def PART_ARRAYLEN(name)
$:fyppmacros.arrayLens[name]
#:enddef PART_ARRAYLEN

#:def ARRAYSLICE(*args)
$:fyppmacros.GenerateArraySlice(*args)
#:enddef ARRAYSLICE



