#include "PPICLF_USER.h"
#include "PPICLF_STD.h"
C Grid
      REAL*8  PPICLF_XDRANGE(2,3)
      COMMON /PPICLF_GRID_RANGE_R/ PPICLF_XDRANGE

      COMMON /PPICLF_GRID_FLD_R/ PPICLF_PRO_FLD,
     >       PPICLF_PRO_FLD_PICL,PPICLF_INT_FLD_INPUT,
     >       PPICLF_INT_FLD,PPICLF_FLUID_GRID,
     >       PPICLF_PICL_GRID,PPICLF_PART2CELL_DIST


      REAL*8 PPICLF_PRO_FLD(PPICLF_LEE,PPICLF_LRP_PRO),
     >       PPICLF_PRO_FLD_PICL(PPICLF_LRP_PRO,PPICLF_LEE),
     >       PPICLF_INT_FLD_INPUT(PPICLF_LEE,PPICLF_LRP_INT),
     >       PPICLF_INT_FLD(PPICLF_LRP_INT,PPICLF_LEE),
     >       PPICLF_FLUID_GRID (PPICLF_LRMAX,PPICLF_LEE),
     >       PPICLF_PICL_GRID  (PPICLF_LRMAX,PPICLF_LEE),
     >       PPICLF_PART2CELL_DIST(PPICLF_LPART,27)

      COMMON /PPICLF_GRID_BIN_MAP_I/PPICLF_CELL_MAP,
     >         PPICLF_CELL_MAP_ORIG,PPICLF_CELL_MAP_INTERP,
     >         PPICLF_CELL_MAP_PROJ,PPICLF_NCELLS_FV2PICL,
     >         PPICLF_NCELLS_FV2PICL_ORIG,PPICLF_NCELLS_INTERP,
     >         PPICLF_NCELLS_PROJ,PPICLF_PART2CELL_MAP,
     >         PPICLF_NPART2CELL
 
     >                        
      INTEGER*4 PPICLF_CELL_MAP(PPICLF_LRMAX,PPICLF_LEE),
     >         PPICLF_CELL_MAP_ORIG(PPICLF_LRMAX,PPICLF_LEE),
     >         PPICLF_CELL_MAP_INTERP(PPICLF_LRMAX,PPICLF_LEE),
     >         PPICLF_CELL_MAP_PROJ(PPICLF_LRMAX,PPICLF_LEE),
     >         PPICLF_NCELLS_FV2PICL, PPICLF_NCELLS_FV2PICL_ORIG,
     >         PPICLF_NCELLS_INTERP, PPICLF_NCELLS_PROJ,
     >         PPICLF_PART2CELL_MAP(PPICLF_LPART,27),
     >         PPICLF_NPART2CELL(PPICLF_LPART)

      INTEGER*4 PPICLF_NFVCELLS
      COMMON /PPICLF_GRID_ORIG_CELL_N/ PPICLF_NFVCELLS

      INTEGER*4 PPICLF_INT_ICNT, PPICLF_INT_MAP(PPICLF_LRP_INT)
      COMMON /PPICLF_INTERP_I/ PPICLF_INT_ICNT, PPICLF_INT_MAP

