#include "PPICLF_USER.h"
#include "PPICLF_STD.h"
c Communication
      COMMON /PPICLF_PARALLEL_COMM_I/ PPICLF_COMM, PPICLF_NP, PPICLF_NID
     >                               ,PPICLF_CR_HNDL, PPICLF_FP_HNDL
     >                               ,PPICLF_COMM_NID, PPICLF_GLNPART
      INTEGER*4 PPICLF_COMM, PPICLF_NP, PPICLF_NID, PPICLF_CR_HNDL
     >         ,PPICLF_FP_HNDL, PPICLF_COMM_NID, PPICLF_GLNPART
      DATA PPICLF_NID /0/

c Bins
      INTEGER*4 PPICLF_N_BINS(3),PPICLF_TOTALBINS 
      COMMON /PPICLF_PARALLEL_BIN_GLOBAL_N/ PPICLF_N_BINS
     >        ,PPICLF_TOTALBINS

      REAL*8 PPICLF_BINS_DX(3), PPICLF_BINB(6), PPICLF_BIN_POS(2,3)
     >       ,PPICLF_PREVIOUSBINB(6)
      COMMON /PPICLF_PARALLEL_BIN_GLOBAL_R/ PPICLF_BINS_DX, PPICLF_BINB
     >        ,PPICLF_BIN_POS, PPICLF_PREVIOUSBINB

C Ghost particles
      REAL*8 PPICLF_RPROP_GP(PPICLF_LRP_GP,PPICLF_LPART_GP)  
     >    ,PPICLF_CP_MAP(PPICLF_LRP_GP,PPICLF_LPART)
      COMMON /PPICLF_PARALLEL_GHOST_R/ PPICLF_RPROP_GP, PPICLF_CP_MAP


      INTEGER*4 PPICLF_IPROP_GP(PPICLF_LIP_GP,PPICLF_LPART_GP)
     >          ,PPICLF_PARTICLEMOVED
      COMMON /PPICLF_PARALLEL_GHOST_I/ PPICLF_IPROP_GP
     >                                ,PPICLF_PARTICLEMOVED

      INTEGER*4  PPICLF_NPART_GP
      COMMON /PPICLF_PARALLEL_GHOST_N/ PPICLF_NPART_GP

      LOGICAL PPICLF_PPINTERACTIONS
      COMMON /PPICLF_PARALLEL_GHOST_L/ PPICLF_PPINTERACTIONS

      INTEGER*4 PARTICLE_NN(PPICLF_LPART)
      COMMON    /PPICLF_PARALLEL_GHOST_N/ PARTICLE_NN
