#!/bin/bash
#SBATCH --job-name=PICLtest
#SBATCH --output=periodicIntp.txt
#SBATCH --error=run.err
#SBATCH --mail-type=none
#SBATCH --ntasks=3
#SBATCH --nodes=1
#SBATCH --mem-per-cpu=20gb                     # Per node
#SBATCH --time=00-00:30:00             # Walltime in hh:mm:ss or d-hh:mm:ss
#SBATCH --account=bala1s
#SBATCH --qos=bala1s
date

module purge 
module load gcc/14.2.0
module load openmpi/5.0.7

EXEC=../PICL_Test

ntasks=$SLURM_NTASKS
nodes=$SLURM_JOB_NUM_NODES

echo "Current Directory =" `pwd`
cd run1
srun -N 1 -n 1 --mpi=${HPC_PMIX} $EXEC -v 2
cd ../run2
srun -N 1 -n 2 --mpi=${HPC_PMIX} $EXEC -v 2
# cd ../run3
# srun -N 1 -n 3 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 4 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 5 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 6 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 7 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 8 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 9 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 10 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 11 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 12 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 13 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 14 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 15 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 16 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 17 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 18 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 19 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 20 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 21 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 22 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 23 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 24 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 25 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 26 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 27 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 28 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 29 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 30 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 31 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 32 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 33 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 34 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 35 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 36 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 37 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 38 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 39 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 40 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 41 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 42 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 43 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 44 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 45 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 46 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 47 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 48 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 49 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 50 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 51 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 52 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 53 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 54 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 55 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 56 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 57 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 58 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 59 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 60 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 61 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 62 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 63 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 64 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 65 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 66 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 67 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 68 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 69 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 70 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 71 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 72 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 73 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 74 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 75 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 76 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 77 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 78 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 79 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 80 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 81 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 82 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 83 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 84 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 85 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 86 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 87 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 88 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 89 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 90 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 91 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 92 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 93 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 94 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 95 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 96 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 97 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 98 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 99 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 100 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 101 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 102 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 103 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 104 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 105 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 106 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 107 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 108 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 109 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 110 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 111 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 112 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 113 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 114 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 115 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 116 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 117 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 118 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 119 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 120 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 121 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 122 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 123 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 124 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 125 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 126 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 127 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 128 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 129 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 130 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 131 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 132 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 133 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 134 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 135 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 136 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 137 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 138 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 139 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 140 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 141 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 142 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 143 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 144 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 145 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 146 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 147 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 148 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 149 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 150 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 151 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 152 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 153 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 154 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 155 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 156 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 157 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 158 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 159 --mpi=${HPC_PMIX} $EXEC -v 2
# srun -N 1 -n 160 --mpi=${HPC_PMIX} $EXEC -v 2
